/**
 * مفاتيح الاستعلام المركزية لـ TanStack Query — تُستخدم لكل الـ invalidations.
 */
export const queryKeys = {
  profile: ['profile'] as const,
  role: ['role'] as const,
  favorites: ['favorites'] as const,
  settings: (key?: string) => ['settings', key ?? 'all'] as const,
  profileContent: (section: string) => ['profile-content', section] as const,
  interests: ['interests'] as const,
  research: (filters?: unknown) => ['research', filters ?? {}] as const,
  researchItem: (slug: string) => ['research', 'item', slug] as const,
  publications: (filters?: unknown) => ['publications', filters ?? {}] as const,
  supervision: (filters?: unknown) => ['supervision', filters ?? {}] as const,
  discussions: (filters?: unknown) => ['discussions', filters ?? {}] as const,
  projects: (filters?: unknown) => ['projects', filters ?? {}] as const,
  projectItem: (slug: string) => ['projects', 'item', slug] as const,
  courses: (filters?: unknown) => ['courses', filters ?? {}] as const,
  lectures: (filters?: unknown) => ['lectures', filters ?? {}] as const,
  axes: ['axes'] as const,
  axisItem: (slug: string) => ['axes', 'item', slug] as const,
  axisContent: (id: string) => ['axes', 'content', id] as const,
  search: (params: unknown) => ['search', params] as const,
  news: (filters?: unknown) => ['news', filters ?? {}] as const,
  newsItem: (slug: string) => ['news', 'item', slug] as const,
  insights: (filters?: unknown) => ['insights', filters ?? {}] as const,
  announcements: ['announcements'] as const,
  calendar: (range: unknown) => ['calendar', range] as const,
  home: {
    stats: ['home', 'stats'] as const,
    categories: ['home', 'categories'] as const,
    latestResearch: ['home', 'latest-research'] as const,
  },
  metrics: (contentType: string, contentId: string) => ['metrics', contentType, contentId] as const,
  contactSubmissions: (filters?: unknown) => ['contact-submissions', filters ?? {}] as const,
  admin: {
    list: (entity: string, params?: unknown) => ['admin', entity, 'list', params ?? {}] as const,
    item: (entity: string, id: string) => ['admin', entity, 'item', id] as const,
    analytics: ['admin', 'analytics'] as const,
    users: (params?: unknown) => ['admin', 'users', params ?? {}] as const,
    auditLogs: ['admin', 'audit-logs'] as const,
    axes: ['admin', 'axes'] as const,
    media: ['admin', 'media'] as const,
    settings: ['admin', 'settings'] as const,
    submissions: (params?: unknown) => ['admin', 'submissions', params ?? {}] as const,
  },
} as const;
